SEED_URLS = [
    # Teams (30 franchises)
    "https://en.wikipedia.org/wiki/Los_Angeles_Lakers",
    "https://en.wikipedia.org/wiki/Golden_State_Warriors",
    "https://en.wikipedia.org/wiki/Boston_Celtics",
    "https://en.wikipedia.org/wiki/Chicago_Bulls",
    "https://en.wikipedia.org/wiki/Miami_Heat",
    "https://en.wikipedia.org/wiki/San_Antonio_Spurs",
    "https://en.wikipedia.org/wiki/Dallas_Mavericks",
    "https://en.wikipedia.org/wiki/Brooklyn_Nets",
    "https://en.wikipedia.org/wiki/Phoenix_Suns",
    "https://en.wikipedia.org/wiki/Milwaukee_Bucks",
    "https://en.wikipedia.org/wiki/Denver_Nuggets",
    "https://en.wikipedia.org/wiki/Philadelphia_76ers",
    "https://en.wikipedia.org/wiki/Oklahoma_City_Thunder",
    "https://en.wikipedia.org/wiki/Cleveland_Cavaliers",
    "https://en.wikipedia.org/wiki/Toronto_Raptors",
    "https://en.wikipedia.org/wiki/New_York_Knicks",
    "https://en.wikipedia.org/wiki/Los_Angeles_Clippers",
    "https://en.wikipedia.org/wiki/Memphis_Grizzlies",
    "https://en.wikipedia.org/wiki/Minnesota_Timberwolves",
    "https://en.wikipedia.org/wiki/New_Orleans_Pelicans",

    # Legends
    "https://en.wikipedia.org/wiki/LeBron_James",
    "https://en.wikipedia.org/wiki/Stephen_Curry",
    "https://en.wikipedia.org/wiki/Kevin_Durant",
    "https://en.wikipedia.org/wiki/Michael_Jordan",
    "https://en.wikipedia.org/wiki/Kobe_Bryant",
    "https://en.wikipedia.org/wiki/Shaquille_O%27Neal",
    "https://en.wikipedia.org/wiki/Magic_Johnson",
    "https://en.wikipedia.org/wiki/Larry_Bird",
    "https://en.wikipedia.org/wiki/Tim_Duncan",
    "https://en.wikipedia.org/wiki/Dirk_Nowitzki",
    "https://en.wikipedia.org/wiki/Allen_Iverson",
    "https://en.wikipedia.org/wiki/Dwyane_Wade",
    "https://en.wikipedia.org/wiki/Chris_Paul",
    "https://en.wikipedia.org/wiki/Paul_Pierce",
    "https://en.wikipedia.org/wiki/Charles_Barkley",
    "https://en.wikipedia.org/wiki/Karl_Malone",
    "https://en.wikipedia.org/wiki/Hakeem_Olajuwon",
    "https://en.wikipedia.org/wiki/Julius_Erving",
    "https://en.wikipedia.org/wiki/Bill_Russell",
    "https://en.wikipedia.org/wiki/Wilt_Chamberlain",

    # Current stars
    "https://en.wikipedia.org/wiki/Giannis_Antetokounmpo",
    "https://en.wikipedia.org/wiki/Nikola_Joki%C4%87",
    "https://en.wikipedia.org/wiki/Luka_Don%C4%8Di%C4%87",
    "https://en.wikipedia.org/wiki/Kawhi_Leonard",
    "https://en.wikipedia.org/wiki/James_Harden",
    "https://en.wikipedia.org/wiki/Russell_Westbrook",
    "https://en.wikipedia.org/wiki/Victor_Wembanyama",
    "https://en.wikipedia.org/wiki/Anthony_Davis",
    "https://en.wikipedia.org/wiki/Jayson_Tatum",
    "https://en.wikipedia.org/wiki/Joel_Embiid",
    "https://en.wikipedia.org/wiki/Damian_Lillard",
    "https://en.wikipedia.org/wiki/Devin_Booker",
    "https://en.wikipedia.org/wiki/Donovan_Mitchell",
    "https://en.wikipedia.org/wiki/Ja_Morant",
    "https://en.wikipedia.org/wiki/Zion_Williamson",
    "https://en.wikipedia.org/wiki/Shai_Gilgeous-Alexander",
    "https://en.wikipedia.org/wiki/Anthony_Edwards_(basketball)",
    "https://en.wikipedia.org/wiki/Paolo_Banchero",

    # NBA Finals
    "https://en.wikipedia.org/wiki/2024_NBA_Finals",
    "https://en.wikipedia.org/wiki/2023_NBA_Finals",
    "https://en.wikipedia.org/wiki/2022_NBA_Finals",
    "https://en.wikipedia.org/wiki/2021_NBA_Finals",
    "https://en.wikipedia.org/wiki/2020_NBA_Finals",
    "https://en.wikipedia.org/wiki/2019_NBA_Finals",
    "https://en.wikipedia.org/wiki/2018_NBA_Finals",
    "https://en.wikipedia.org/wiki/2016_NBA_Finals",
    "https://en.wikipedia.org/wiki/NBA_Finals",

    # League & Awards
    "https://en.wikipedia.org/wiki/NBA",
    "https://en.wikipedia.org/wiki/NBA_Most_Valuable_Player_Award",
    "https://en.wikipedia.org/wiki/NBA_All-Star_Game",
    "https://en.wikipedia.org/wiki/List_of_NBA_champions",
    "https://en.wikipedia.org/wiki/NBA_Defensive_Player_of_the_Year_Award",
    "https://en.wikipedia.org/wiki/NBA_Rookie_of_the_Year_Award",
    "https://en.wikipedia.org/wiki/NBA_draft",
    "https://en.wikipedia.org/wiki/Eastern_Conference_(NBA)",
    "https://en.wikipedia.org/wiki/Western_Conference_(NBA)",
]
